# Generated by Django 3.1.1 on 2020-09-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'second_name')},
        ),
    ]
