# Generated by Django 3.1.1 on 2020-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200929_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isCustomersWhoMadePurchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase',
            field=models.CharField(default='', max_length=30),
        ),
    ]
