# Generated by Django 3.1.1 on 2020-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200929_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchase',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
