# Generated by Django 3.1.1 on 2020-09-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200929_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='purchase',
            new_name='purchaseXD',
        ),
    ]
