# Generated by Django 3.1.1 on 2020-09-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200929_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(choices=[('hero', 'Hero'), ('story', 'Our Story')], default='hero', max_length=250),
        ),
    ]
