openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /customer/:
    get:
      operationId: listCustomers
      description: ''
      parameters:
      - name: isCustomersWhoMadePurchase
        required: false
        in: query
        description: isCustomersWhoMadePurchase
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    post:
      operationId: createCustomer
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
  /customer{format}:
    get:
      operationId: retrieveCustomer
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: isCustomersWhoMadePurchase
        required: false
        in: query
        description: isCustomersWhoMadePurchase
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer{format}
    post:
      operationId: createCustomer
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer{format}
  /customer/{id}/:
    get:
      operationId: retrieveCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    put:
      operationId: updateCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    patch:
      operationId: partialUpdateCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    delete:
      operationId: destroyCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - customer
  /customer/{id}{format}:
    get:
      operationId: retrieveCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    put:
      operationId: updateCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    patch:
      operationId: partialUpdateCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Customer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
          description: ''
      tags:
      - customer
    delete:
      operationId: destroyCustomer
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this customer.
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - customer
components:
  schemas:
    Customer:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 50
        second_name:
          type: string
          maxLength: 50
        telephone:
          type: integer
        email:
          type: string
          format: email
          maxLength: 254
        isCustomersWhoMadePurchase:
          type: boolean
        purchase:
          enum:
          - red
          - green
          - blue
          - none
          type: string
      required:
      - first_name
      - second_name
      - telephone
      - email
